// Mocks generated by Mockito 5.4.6 from annotations
// in sqa_multitools/test/plugins/todo/todo_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqa_multitools/plugins/todo/models/recurring_todo.dart' as _i6;
import 'package:sqa_multitools/plugins/todo/models/todo_item.dart' as _i5;
import 'package:sqa_multitools/plugins/todo/models/todo_settings.dart' as _i2;
import 'package:sqa_multitools/plugins/todo/services/todo_storage_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTodoSettings_0 extends _i1.SmartFake implements _i2.TodoSettings {
  _FakeTodoSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoStorageService extends _i1.Mock
    implements _i3.TodoStorageService {
  MockTodoStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveTodos(List<_i5.TodoItem>? todos) =>
      (super.noSuchMethod(
            Invocation.method(#saveTodos, [todos]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TodoItem>> loadAllTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllTodos, []),
            returnValue: _i4.Future<List<_i5.TodoItem>>.value(<_i5.TodoItem>[]),
          )
          as _i4.Future<List<_i5.TodoItem>>);

  @override
  _i4.Future<void> saveRecurringTodos(List<_i6.RecurringTodo>? recurring) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecurringTodos, [recurring]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.RecurringTodo>> loadRecurringTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecurringTodos, []),
            returnValue: _i4.Future<List<_i6.RecurringTodo>>.value(
              <_i6.RecurringTodo>[],
            ),
          )
          as _i4.Future<List<_i6.RecurringTodo>>);

  @override
  _i4.Future<void> saveSettings(_i2.TodoSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.TodoSettings> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i4.Future<_i2.TodoSettings>.value(
              _FakeTodoSettings_0(this, Invocation.method(#loadSettings, [])),
            ),
          )
          as _i4.Future<_i2.TodoSettings>);

  @override
  _i4.Future<void> pruneOldFiles(int? retentionDays) =>
      (super.noSuchMethod(
            Invocation.method(#pruneOldFiles, [retentionDays]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
