// Mocks generated by Mockito 5.4.6 from annotations
// in sqa_multitools/test/core/services/linux_integration_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:logging/logging.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i4;
import 'package:sqa_multitools/core/services/logging_service.dart' as _i2;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i2.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.LogRecord> get logs =>
      (super.noSuchMethod(
            Invocation.getter(#logs),
            returnValue: <_i3.LogRecord>[],
          )
          as List<_i3.LogRecord>);

  @override
  _i4.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i5.dummyValue<_i4.Ref>(this, Invocation.getter(#ref)),
          )
          as _i4.Ref);

  @override
  set state(dynamic newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  void build() => super.noSuchMethod(
    Invocation.method(#build, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String?> getLogFilePath() =>
      (super.noSuchMethod(
            Invocation.method(#getLogFilePath, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  void logInfo(String? message, [String? name]) => super.noSuchMethod(
    Invocation.method(#logInfo, [message, name]),
    returnValueForMissingStub: null,
  );

  @override
  void logWarning(
    String? message, [
    String? name,
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#logWarning, [message, name, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void logError(
    String? message, [
    String? name,
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#logError, [message, name, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void logDebug(String? message, [String? name]) => super.noSuchMethod(
    Invocation.method(#logDebug, [message, name]),
    returnValueForMissingStub: null,
  );

  @override
  void runBuild() => super.noSuchMethod(
    Invocation.method(#runBuild, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.RemoveListener listenSelf(
    void Function(void, void)? listener, {
    void Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listenSelf, [listener], {#onError: onError}),
            returnValue: () {},
          )
          as _i7.RemoveListener);

  @override
  bool updateShouldNotify(dynamic previous, dynamic next) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
