// Mocks generated by Mockito 5.4.6 from annotations
// in sqa_multitools/test/core/plugin_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:sqa_multitools/core/services/preferences_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i3.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get rawPrefs =>
      (super.noSuchMethod(
            Invocation.getter(#rawPrefs),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#rawPrefs),
            ),
          )
          as _i2.SharedPreferences);

  @override
  _i4.Future<void> setEnabledPluginIds(List<String>? pluginIds) =>
      (super.noSuchMethod(
            Invocation.method(#setEnabledPluginIds, [pluginIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPluginOrder(List<String>? order) =>
      (super.noSuchMethod(
            Invocation.method(#setPluginOrder, [order]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getThemeModeIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeModeIndex, []),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> setThemeModeIndex(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeModeIndex, [index]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getSeedColorValue() =>
      (super.noSuchMethod(
            Invocation.method(#getSeedColorValue, []),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> setSeedColorValue(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSeedColorValue, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool getUseDynamicColor() =>
      (super.noSuchMethod(
            Invocation.method(#getUseDynamicColor, []),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> setUseDynamicColor(bool? useDynamic) =>
      (super.noSuchMethod(
            Invocation.method(#setUseDynamicColor, [useDynamic]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getSupporterTier() =>
      (super.noSuchMethod(
            Invocation.method(#getSupporterTier, []),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> setSupporterTier(int? tier) =>
      (super.noSuchMethod(
            Invocation.method(#setSupporterTier, [tier]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSupporterCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#setSupporterCode, [code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int getBugsSquashed() =>
      (super.noSuchMethod(
            Invocation.method(#getBugsSquashed, []),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> setBugsSquashed(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setBugsSquashed, [count]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool getBugSquashEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getBugSquashEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> setBugSquashEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBugSquashEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
